# Lab Notebook 2 – More Python use cases

This week's materials are designed to cover some more of the basic of Python not covered in the first practicals.   
We will be introducing:  

- 1) a new data type: [Dictionaries](https://realpython.com/python-dicts/) or `dict` – which are used to store a collection of key-value pairs (e.g. key is name and value is Bob).
- 2) Numpy arrays  – which can store data in order like a Python `list`
- 3) Nesting and loops
- 4) Functions – which allow us to reuse blocks of code

# Dictionaries
Python dictionaries (dict) are a data structure that store **key:value** pairs. They are useful as they allow us to 'lookup' data using a 'key'.  In a list we can store lots of values, and access a specific value by its position in the list (its index).
In a dictionary we access data by using its key.
The syntax to do this is ``dictionaryName[key]``.  
The general syntax to define a new dictionary variable is:
```python
    name_of_dict = {'my_key':'my_var'}
```

In [6]:
employee = {'name':'Bob', 
           'age': 25, 
           'job':'Dev', 
           'city': 'New York', 
           'email': ['bob@web.com', 'bob@email.com']}


#### 🤨 TASK
We know that the `employees` variable we defined in the cell below is a dictionary, but how would you check its type in Python?  
*Replace the `???` below with your answer*

In [4]:
print(type(employee))
type(employee)


<class 'dict'>


dict

We can 'lookup' dictionaries using their keys 

In [7]:
print(employee['job'])


Dev


In [8]:
# Bit of a waste of memory, but we can store values from a dictionary lookup into variables 
employee_name = employee['name']
employee_age = employee['age']

print(f"Employee {employee_name} is {employee_age} years old") # this is an f-string, and allows us to put variables within a string 


Employee Bob is 25 years old


#### 🤨 optional TASK
Remembering that we can loop over iterable variables like lists of dictionaries using `for` loops. Find out the type of each item in the `my_dict` variable
*Replace the `???` below with your answer*

In [16]:
for key in employee:
    value = employee[key]
    print(key, value, type(value))

for key, value in employee.items():
    print(key, value, type(value))


name Bob <class 'str'>
age 25 <class 'int'>
job Dev <class 'str'>
city New York <class 'str'>
email ['bob@web.com', 'bob@email.com'] <class 'list'>
name Bob <class 'str'>
age 25 <class 'int'>
job Dev <class 'str'>
city New York <class 'str'>
email ['bob@web.com', 'bob@email.com'] <class 'list'>


#### 🤨 TASK
What happens if you try to access a value from the dictionary using a key that doesn't exist in it?  
*Replace the `???` below with your answer*

In [17]:
employee['address']
# It triggers an error message!


KeyError: 'address'

The next cells give an example of a dictionary in which the keys are British cities and the values are the populations, and shows how to access a value from the dictionary.

In [23]:
city_populations = {
    'St Davids': 1841, 
    'St Asaph': 3355, 
    'City of London': 7375, 
    'Wells': 10536, 
    'Armagh': 14777, 
    'Ripon': 16702
}

# to access a value from a dictionary use dictionaryName[key]
populationOfWells = city_populations['Wells']
print('The population of Wells is', populationOfWells)

# the key could be stored in a variable.
# Change the value of this variable and see that the output of the next line changes.
cityName = 'Ripon'
print(f'The population of {cityName} is {city_populations[cityName]}')


The population of Wells is 10536
The population of Ripon is 16702


In [25]:
for city, population in city_populations.items():
    print(f'The population of {city} is {population}.')


The population of St Davids is 1841.
The population of St Asaph is 3355.
The population of City of London is 7375.
The population of Wells is 10536.
The population of Armagh is 14777.
The population of Ripon is 16702.


An alternative way to access a dictionary item is to use ``get()``.
This will not cause an error if the key doesn't exist in the dictionary.
If the key doesn't exist then ``get()`` will return None by default.

In [26]:
city_populations = {
    'St Davids': 1841, 
    'St Asaph': 3355, 
    'City of London': 7375, 
    'Wells': 10536, 
    'Armagh': 14777, 
    'Ripon': 16702
}

print(city_populations.get('Wells'))
print(city_populations.get('Not a City'))


10536
None


### Adding and Removing Items From a Dictionary
To add a key, value pair to a dictionary use ``update()``. 
We can update with a single item or a list of key: value pairs. 

In [27]:
city_populations = {
    'St Davids': 1841, 
    'St Asaph': 3355, 
    'Ripon': 16702
}

# update with a single item
city_populations.update({"Truro": 18766})

print(city_populations)

city_populations.update({
    'City of London': 7375, 
    'Wells': 10536, 
    'Armagh': 14777
})

print(city_populations)


{'St Davids': 1841, 'St Asaph': 3355, 'Ripon': 16702, 'Truro': 18766}
{'St Davids': 1841, 'St Asaph': 3355, 'Ripon': 16702, 'Truro': 18766, 'City of London': 7375, 'Wells': 10536, 'Armagh': 14777}


And to remove an item from the dictionary use ``pop()``.

In [28]:
city_populations = {
    'St Davids': 1841, 
    'St Asaph': 3355, 
    'City of London': 7375, 
    'Wells': 10536, 
    'Armagh': 14777, 
    'Ripon': 16702
}

# the pop() function returns the value of the item being removed
print(city_populations.pop('Wells'))

# now the item with key 'Wells' no longer appears in the dictionary
print(city_populations)


10536
{'St Davids': 1841, 'St Asaph': 3355, 'City of London': 7375, 'Armagh': 14777, 'Ripon': 16702}


Remove all items of a dictionary with ``clear()``.

In [29]:
city_populations = {
    'St Davids': 1841, 
    'St Asaph': 3355, 
    'City of London': 7375, 
    'Wells': 10536, 
    'Armagh': 14777, 
    'Ripon': 16702
}

city_populations.clear()

# now an empty dictionary
print(city_populations)


{}


# Numpy arrays
Next, we will look at numpy arrays, which are a data structure similar, but more powerful, than Python's lists. Numpy is a popular 3rd party library that introduces a range of numerical methods and tools, which does not come default with Python, but it is easy to install. 

Numpy arrays, as opposed to lists, allow us to perform multi-dimensional operations such as matrix multiplication/division/etc and mutli-dimensional indexing (which is why lots of other third party packages use numpy arrays or matrices as their building blocks).

In the cell below we import numpy with an alias: `np`. While we could import numpy without an alias (made by using the `as` statement), it is common to use the shorthand for popular packages such numpy (another example is for pandas e.g. `import pandas as pd`). This is another example of Pythonic syntax that you just remember with time.

In [30]:
import numpy as np


Let's look at lists and numpy arrays side by side. 


In [32]:
my_array = np.array([1, 2, 3, 4])
my_list = [1, 2, 3, 4]
print(my_array, my_list)


[1 2 3 4] [1, 2, 3, 4]


We will perform an arithmetic operation on each.

In [33]:
my_array + 10


array([11, 12, 13, 14])

In [43]:
my_list + 4


[1, 2, 3, 4, 4]

You should find that the operation above returns a TypeError, that is because it is of type `list`, which does not open up mathematical operations like numpy arrays do. This is super useful for scientific computing

#### 🤨 TASK
Try getting the value at the second index of `my_array`, does it perform in the way you would expect?  
*Replace the `???` below with your answer*

In [44]:
my_array[1]

# Yes, it does! (Indexing works the same as for lists!)


2

Sometimes this functionality can create confusion. See the example below where we try to add a list with a single numerical value `[1]` to a list and numpy array.

In [42]:
# Perform an arithmetic operation on the NumPy array
print(my_array + [1])

# Perform an arithmetic operation on the Python list
print(my_list + [1])


[2 3 4 5]
[1, 2, 3, 4, 1]


*NOTE:* A good working knowlegde of data-types and their operability in Python will help you become more comfortable with this sort of edge case in the future. As you can imagine, this sort of thing is hard to teach, but familiarity and experience will get you there. And a key tip is to just experiment in an empty cell to aid your understanding whenever you can.

In [52]:
# Create a NumPy array from a Python list
my_list = [1,2,3,4,5,6,7,8,9,10]
my_array = np.array(my_list)
print(my_array)


[ 1  2  3  4  5  6  7  8  9 10]


Next, we look at other numpy functions that produce numpy arrays

In [53]:
# Create a NumPy array of zeros
zeros_array = np.zeros(10)


In [54]:
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
# Create a NumPy array of ones
ones_array = np.ones(10)


In [56]:
print(ones_array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


More operations for numpy arrays 

In [59]:
# Add two NumPy arrays
sum_array = my_array + ones_array
print(sum_array)


[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [60]:
# Subtract two NumPy arrays
difference_array = my_array - ones_array
print(difference_array)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [61]:
# Multiply two NumPy arrays
twos_array = ones_array * 2
product_array = my_array * twos_array
print(product_array)


[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


#### 🤨 TASK
Try dividing one array by another  
*Replace the `???` below with your answer*

In [63]:
division_array = my_array / my_array
print(division_array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In the cell below, we can look at some of the many mathematical operations offered by numpy

In [64]:
# Calculate the mean of a NumPy array
mean = np.mean(my_array)
print(mean)

# Calculate the median of a NumPy array
median = np.median(my_array)
print(median)

# Calculate the standard deviation of a NumPy array
standard_deviation = np.std(my_array)
print(standard_deviation)


5.5
5.5
2.8722813232690143


In [65]:
# Sort a NumPy array in ascending order
sorted_array = np.sort(my_array)
print(sorted_array)
# Sort a NumPy array in descending order
sorted_array = np.sort(my_array)[::-1]
print(sorted_array)


[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [70]:
my_array[::-2]


array([10,  8,  6,  4,  2])

In [71]:
# Filter a NumPy array to only include elements that are greater than 2
filtered_array = my_array[my_array > 2]
print(filtered_array)

# Filter a NumPy array to only include elements that are even
filtered_array = my_array[my_array % 2 == 0]
print(filtered_array)


[ 3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [79]:
# Create a NumPy array of random integers between 0 and 10
random_integers = np.random.randint(0, 10, 10)
print(random_integers)


[2 0 3 8 1 3 8 6 0 6]


# Loops and nesting
Next, we briefly introduce a concept known as nesting. This is where a loop is included within a loop. While the Python Syntax of nested loops may look a little complex at first, it follows a very simple rule of 4 spaces (one tab). See an example below...

In [80]:
for i in range(1, 4):
    # outer
    print(i) # 4 spaces away from the edge
    for j in range(10, 13):
        # inner
        print(j) # 8 spaces away from the edge


1
10
11
12
2
10
11
12
3
10
11
12


We can also include conditions (introduced in last weeks practical) to control the flow of nested loops. In the cell below we search for even and odd numbers and only pass through even numbers to the inner loop.  

We also introduce a new operator: the modulo `%` operator here. This operator returns the remainder after division between two numbers. While, it is not vital that you understand modolo and its uses at this point, if you would like to understand the operator a little more, I recommend experimenting with it in a new cell.

In [83]:
for i in range(6):
    # outer loop
    if i % 2 == 0: # only even numbers will pass this condition
        print("even", i)
        for j in range(1, 4):
            # inner loop
            print("inner loop", j)
    else:
        print("odd", i)


even 0
inner loop 1
inner loop 2
inner loop 3
odd 1
even 2
inner loop 1
inner loop 2
inner loop 3
odd 3
even 4
inner loop 1
inner loop 2
inner loop 3
odd 5


As you may imagine, you can nest further i.e. to three, four or five levels. And while this is useful in some circumstances, it is usually consider non-Pythonic. See an example of three nests below

In [84]:
for i in range(1, 2):
    # outer
    for j in range(10, 13):
        # inner
        for k in range(20, 23):
            # more inner
            print(i, j, k)


1 10 20
1 10 21
1 10 22
1 11 20
1 11 21
1 11 22
1 12 20
1 12 21
1 12 22


While three is still just about comprehensible, with further nesting can (and will) create confusion for others trying to follow your code _(more nesting == less readibility)_, and you can create computational problems (as exponentially more operations need to be done with more nesting). Instead of relying only on loops to repeat over code, we can can lean on functional programming. This is one of Python's key strengths as it allows us to reduce the amount of repeated code. We introduce user defined functions in Python next...

# Functions

Functions are very useful for breaking our code down into components. This makes the code easier to understand and allows us to reuse blocks of code easily (without copying and pasting!).

The first line tells Python that we're going to define a new function with the ``def`` keyword, and it gives the name of the function and any parameters it will take.

Every line of the body of the function must be indented, this is how Python knows that the line belongs to the function and not to the main code.

In [98]:
def sayHello(name):
    print('Hello', name)

sayHello('Ben')

def marie_antoinette(name):
    if name == 'Marie-Antoinette':
        print(name, 'is not as great as THE Marie-Antoinette')
    else: 
        print(name, 'is not as great as Marie-Antoinette')

marie_antoinette('Marie-Antoinette')
marie_antoinette('Macron')


Hello Ben
Marie-Antoinette is not as great as THE Marie-Antoinette
Macron is not as great as Marie-Antoinette


### The Return Statement
As well as doing things within a function we often want to return a value to the calling code. This is done with the return keyword.

In [100]:
def volumeOfCube(lengthOfEdge):
    # the length of the edge cubed
    vol = pow(lengthOfEdge,3)
    return vol

volume = volumeOfCube(5)
print(f"Volume is {volume}")


Volume is 125


Functions give us a way to abstract what we're doing.
For example, calculating the volume of a cube is a special case of calculating the volume of a cuboid, which is a special case of calculating the volume of a prism

In [101]:
def volumeOfPrism(baseArea, height):
    return baseArea * height

def areaOfRectangle(l1, l2):
    return l1 * l2

def volumeOfCuboid(l1, l2, l3):
    baseArea = areaOfRectangle(l1, l2)
    vol = volumeOfPrism(baseArea, l3)
    return vol

def volumeOfCube(lengthOfEdge):
    return volumeOfCuboid(lengthOfEdge, lengthOfEdge, lengthOfEdge)

volumeOfCube(5)


125

Returning multiple values is easy, Python packs the values into a tuple and will also unpack the tuple to assign the return values to multiple variables.

In [103]:
def getSumAndLength(listOfInts):
    return sum(listOfInts), len(listOfInts)

# function returns two values which are assigned to two variables
s, l = getSumAndLength([1, 2, 3])

print(f'sum of numbers = {s}')
print(f'length of list = {s}')


sum of numbers = 6
length of list = 6


#### 🤨 TASK
A pizza restaurant wants to make their kitchen more efficient.
They intend to have one chef responsible for making all the bases, another chopping items for the toppings, another preparing the cheese.
Then the head chef can easily assemble all the parts and put the pizza in the oven.

To make this happen the restaurant requires a system that processes each order and updates a job list for each worker.
When a pizza is ordered the required base, cheese and toppings are added to dictionaries which tell the different chefs what they need to prepare.
For example, if a pizza is ordered with mushrooms for the topping then the value of 'mushrooms' in the toppings dictionary should be increased by one.

A base type must always be specified, the cheese type should default to Mozarella but there is a gluten free option.
Any number of additional toppings can then be requested, including zero.
Create a function which fulfils these requirements and updates the dictionaries shown below when a pizza is ordered.

You can assume that the inputs are always valid, but if you want an extra challenge then think about how you could check for errors (e.g. trying to order a topping which is not available).

Check that your function works by calling it with a couple of different pizza orders and printing out the dictionaries.

In [ ]:
toppings = {
    'pepperoni': 0,
    'olives': 0,
    'red_peppers': 0,
    'green_peppers': 0,
    'mushrooms': 0,
    'chicken': 0,
    'stilton': 0,
    'ricotta': 0,
}

base = {
    'thin': 0,
    'deep_pan': 0,
    'gluten_free': 0
}

cheese = {
    'mozzarella': 0,
    'dairy_free': 0
}

def orderPizza(baseType, *toppingTypes, cheeseType = 'mozzarella'):
    global toppings, base, cheese
    # this line is not necessary but it makes it clear that we are updating the global variables

    # *toppingTypes is a tuple of all the toppings for the pizza
    # default cheese type is mozzarella

    # Now update the dictionaries toppings, base and cheese using arguments to orderPizza
    return


#### 🤨 TASK
Suppose you've been given name and address information from a database.
Create functions to format this information so that it can be printed onto address labels.
For example, the entry

```['Mrs', 'Joan', 'Smith', '3 Huntsmans Avenue', 'Batley', 'WF17 3RW']```

should print as

Mrs J. Smith
3 Huntsmans Avenue
Batley
WF17 3RW


In [ ]:
mailingList = [
    ['title', 'fname', 'sname', 'addr1', 'addr2', 'postcode'],
    ['Mrs', 'Joan', 'Smith', '3 Huntsmans Avenue', 'Batley', 'WF17 3RW'],
    ['Mr', 'Fred', 'Jones', '15a Brighton Road', 'Wyke', 'BD6 4NN'],
    ['Dr', 'Maria', 'Tan', '122 High Street', 'Ilkley', 'LS29 2AD']
]

def prettyPrintAddressLabels(recipients):
    for i, record in enumerate(recipients):
    # format the entry

    # return a list of formatted entries
    return

prettyPrintAddressLabels(mailingList)


# Extra
### Getting ahead of the curve...
In the weeks that follow, we will be introducing some of Python's main data manipulation and visualisation libraries. 
These are Pandas (https://pandas.pydata.org/), Numpy (https://numpy.org/), and Matplotlib (https://matplotlib.org/) .
These libraries are absolutely vital for data science in Python (and probably the most popular third-party libraries in the entire language), and you will find that these packages will help you solve a majority of problems in Python. They are also extremely versatile and there are a lot more Python packages that build on top of these three.  
